#!/bin/sh
##   The contents of this file are subject to the Mozilla Public License
##   Version 1.1 (the "License"); you may not use this file except in
##   compliance with the License. You may obtain a copy of the License at
##   https://www.mozilla.org/MPL/
##
##   Software distributed under the License is distributed on an "AS IS"
##   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
##   License for the specific language governing rights and limitations
##   under the License.
##
##   The Original Code is RabbitMQ BQL Plugin.
##
##   The Initial Developers of the Original Code are LShift Ltd.
##
##   Copyright (C) 2009 LShift Ltd.
##
##   All Rights Reserved.
##
##   Contributor(s): ______________________________________.
##

CURDIR=`dirname $0`
RLWRAP=`which rlwrap`

exec $RLWRAP erl \
    -pa "`dirname $0`/ebin" \
    -kernel error_logger silent \
    -noshell \
    -hidden \
    -sname amqpbql$$ \
    -s bql_shell \
    $@
